"""empty message

Revision ID: 7ab980e808a5
Revises: dc076d5091d2
Create Date: 2025-04-30 06:21:51.351617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab980e808a5'
down_revision: Union[str, None] = 'dc076d5091d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_messages', sa.Column('aggregate_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_messages', 'aggregate_id')
    # ### end Alembic commands ###
