"""empty message

Revision ID: dc076d5091d2
Revises: 
Create Date: 2025-04-29 07:01:46.919242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc076d5091d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='orderstate'), nullable=False),
    sa.Column('rejection_reason', sa.Enum('INSUFFICIENT_CREDIT', 'UNKNOWN_CUSTOMER', name='rejectionreason'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_total', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_messages',
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('processed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_messages')
    op.drop_table('orders')
    # ### end Alembic commands ###
