"""empty message

Revision ID: 954fcfe48024
Revises: b6ec969074fb
Create Date: 2025-04-30 06:58:05.354920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954fcfe48024'
down_revision: Union[str, None] = 'b6ec969074fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_reservations', sa.Column('order_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_reservations', 'order_id')
    # ### end Alembic commands ###
