"""empty message

Revision ID: abf4b328c3f6
Revises: 954fcfe48024
Create Date: 2025-04-30 07:00:48.718150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf4b328c3f6'
down_revision: Union[str, None] = '954fcfe48024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_reservations', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('customers', 'money_limit',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'money_limit',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('credit_reservations', 'amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
